bool	alf_wczes		args( ( const char *astr, const char *bstr ) );
char	*capitalize		args( ( const char *str ) );
bool	czy_bluzg		args( ( const char *arg ) );
bool	czy_do_wszystkich	args( ( char *arg ) );
bool	czy_mail		args( ( char *arg ) );
bool	czy_monety		args( ( char *arg ) );
bool	czy_we			args( ( const char *slowo ) );
bool	czy_wszyscy		args( ( char *arg ) );
bool	czy_bluzg1		args( ( const char *arg ) );
bool	czy_wszystko		args( ( char *arg ) );
bool	czy_ze			args( ( const char *slowo ) );
int	dice			args( ( int number, int size ) );
int	drzwi_d			args( ( char *slowo ) );
char	*formatuj_liczbe	args( ( int arg ) );
int	ile_kolorow		args( ( const char *arg ) );
void	init_rng		args( ( void ) );
int	interpolate		args( ( int level, int value_00, int value_32 ) );
bool	is_ipaddr		args( ( char *arg ) );
bool	is_name			args( ( const char *str, char *namelist ) );
bool	is_name2		args( ( const char *str, const char *namelist ) );
bool	is_number		args( ( char *arg ) );
char	*itopl			args( ( unsigned int l, int plec ) );
int	liczba			args( ( int l ) );
bool	miodek			args( ( CHAR_DATA *ch, char *arg ) );
bool	miodek_opisowy		args( ( CHAR_DATA *ch, char *arg ) );
int	number_argument		args( ( char *argument, char *arg ) );
int	number_bits		args( ( int width ) );
int	number_door		args( ( void ) );
int	number_fuzzy		args( ( int number ) );
int	number_percent		args( ( void ) );
int	number_range		args( ( int from, int to ) );
void	odkoloruj		args( ( const char *arg, char *bufor ) );
char	*one_argument		args( ( const char *argument, char *arg_first ) );
char	*one_argument2		args( ( char *argument, char *arg_first ) );
char	*przemiel_opis		args( ( CHAR_DATA *ch, char *opis ) );
char	*slowny_ciezar		args( ( int ciezar ) );
void	smash_tilde		args( ( char *str ) );
bool	str_cmp			args( ( const char *astr, const char *bstr ) );
bool	str_infix		args( ( const char *astr, const char *bstr ) );
int	strlen_pl		args( ( const char *txt ) );
int	strlen_pl_kol		args( ( const char *txt ) );
int	strlen_pl_kol_miel	args( ( const char *txt ) );
bool	str_prefix		args( ( const char *astr, const char *bstr ) );
bool	str_suffix		args( ( const char *astr, const char *bstr ) );
char	*wyrownaj		args( ( const char *text, int dlug ) );
int	zetnij			args( ( int limit, int tempo, int x ) );
void	zjedz_entery_z_konca	args( ( char **lancuch ) );
int	zlicz_bity		args( ( unsigned int liczba ) );
char	*zlota_moneta		args( ( int ile, bool fMianownik, bool fIle ) );
int	znajdz_adres_pl_kol	args( ( const char *txt, int literka ) );
char	*zwielkoliteruj		args( ( const char *str ) );

struct miodek_data	*znajdz_miodka	args( ( const char *arg ) );
