DECLARE_SPELL_FUN(	spell_aniol_stroz	);
DECLARE_SPELL_FUN(	spell_boski_pyl		);
DECLARE_SPELL_FUN(	spell_cud		);
DECLARE_SPELL_FUN(	spell_duchowa_zbroja	);
DECLARE_SPELL_FUN(	spell_jednosc_bojowa	);
DECLARE_SPELL_FUN(	spell_jednosc_obronna	);
DECLARE_SPELL_FUN(	spell_kradziez_zycia	);
DECLARE_SPELL_FUN(	spell_nalozenie_rak	);
DECLARE_SPELL_FUN(	spell_niezlomna_wiara	);
DECLARE_SPELL_FUN(	spell_pozytywne_doladowanie);
DECLARE_SPELL_FUN(	spell_sila_jednosci	);
DECLARE_SPELL_FUN(	spell_spadajace_gwiazdy	);
DECLARE_SPELL_FUN(	spell_strazniczy_glif	);
DECLARE_SPELL_FUN(	spell_stworzenie_grabiezcy);
DECLARE_SPELL_FUN(	spell_stworzenie_mlota	);
DECLARE_SPELL_FUN(	spell_swieta_aura	);
DECLARE_SPELL_FUN(	spell_tarcza_archaniolow);
DECLARE_SPELL_FUN(	spell_wrzaca_krew	);

DECLARE_DO_FUN(	do_rozblysk	);
